version: '3.8'

services:
  diabetes_prediction:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./mlflow_artifacts:/opt/diabetes_prediction/mlflow_artifacts
    command: bash -c "python3 src/app.py & mlflow server --default-artifact-root ./mlflow_artifacts --host 0.0.0.0 --port 5001"
