apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diabetes-prediction
  template:
    metadata:
      labels:
        app: diabetes-prediction
    spec:
      containers:
      - name: diabetes-prediction
        image: gcr.io/[YOUR_PROJECT_ID]/diabetes-prediction:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
