apiVersion: v1
kind: Service
metadata:
  name: diabetes-prediction
spec:
  selector:
    app: diabetes-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
