replicaCount: 3

image:
  repository: gcr.io/[YOUR_PROJECT_ID]/diabetes-prediction
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
