name: ML Pipeline

on:
  push:
    branches:
      - main
      - 'users/*'
      - 'features/*'
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Linting
        run: pylint simple-ml.py

      - name: Deploy
        run: python simple-ml.py
